apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-backend
  namespace: showcase
  labels:
    app: showcase-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: showcase-backend
  template:
    metadata:
      labels:
        app: showcase-backend
    spec:
      containers:
        - name: showcase-backend
          image: quay.io/showcase/showcase:deb10d372aa0e23b80b60741dee3a70c523e2050
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: showcase-backend-secrets
                  key: database-url
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2500m
              memory: 1024Mi

