apiVersion: batch/v1
kind: Job
metadata:
  name: showcase-migrate
  namespace: showcase
  annotations:
    # lets make this migration a hook that runs before sync in argocd and never runs after hook runs without problems
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: showcase-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: quay.io/showcase/showcase:0a094c895bc5a7d2a4f31fc78c6a381a5e34d34f
          command: ["/migrate"]
          # we need to give the database url from secrets in kubernetes to run this job 
          # because this job will migrate the table from ent to database
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: showcase-backend-secrets
                  key: DATABASE_URL

