apiVersion: batch/v1
kind: Job
metadata:
  name: showcase-migrate
  namespace: showcase
  annotations:
    # lets make this migration a hook that runs before sync in argocd and never runs after hook runs without problems
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: showcase-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: quay.io/showcase/showcase:cd42f0d1eec8d410494a0167a5a90cf56771e4ae
          command: ["/migrate"]
          # we need to give the database url from secrets in kubernetes to run this job 
          # because this job will migrate the table from ent to database
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: showcase-backend-secrets
                  key: DATABASE_URL

